### ISSUE TITLE
请问manage目录必须为这个名字是哪里配置的？

### ISSUE THREAD

**Issue by Ignorantforce** [lizhoukai/vue-mobile-cli#1]
尝试修改过该目录名字，运行就报错。

**Comment by lizhoukai** [comment]
@Ignorantforce 没有哦，manage目录只是存放当前模块页面的路由和是 vuex状态。你看下是否app.js 是否有引用manage目录下的 js 文件

**Comment by Ignorantforce** [comment]
@lizhoukai 不好意思，写问题的时候没说清楚情况。
我是尝试按照你的Index里的结构复制了一份。
然后删除了store和router，包括app.js里的引入也删掉了，并且改了目录名（manage）
运行的时候就报错了。

> VM141:87 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-cEmJ9wfQpnZLR35+jGeZk1WmknBbXo0CyiXREeJHUGo='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

我现在的疑问是不配置vuex和vue-router的话，就没办法运行。
不好意思，webpack这块我才准备开始学习，谢谢

**Comment by lizhoukai** [comment]
@Ignorantforce  他提示不要内联样式或脚本，不知道你现在的代码是什么。具体可以看下[这篇文章](http://stackoverflow.com/questions/17766817/refused-to-apply-inline-style-because-it-violates-the-following-content-security)
