### ISSUE TITLE
请问我网站多个展示类静态页面如何放置才合理呢？

### ISSUE THREAD

**Issue by LIANGWEIBIAO** [lizhoukai/vue-mobile-cli#2]
http://upload.ouliu.net/i/20170409040252j4fgn.png

如图，我网站有十多个展示类的静态页面可以放在同一个文件夹里面吗？，看你的项目结构，好似是一个页面对应一个文件夹。

**Comment by lizhoukai** [comment]
你这样设计的时候，你这些静态页面的 css 或者 js资源呢，纯 link 引入吗？这样就不太符合 webpack 模块化处理资源的方式了。因现在这脚手架是基于 vue 的开发模式，model 下 一个文件代表一个 vue 实例页面。所以我建议你model 新建多个目录。

**Comment by LIANGWEIBIAO** [comment]
项目以展示为主，很多页面用不到vue，甚至连js也不用写，一个目录放一个这样的页面太浪费了，而且这样的页面非常多。

**Comment by lizhoukai** [comment]
@LIANGWEIBIAO 那可能不太适合，我这脚手架就是基于 vue 多页设计的。而不是纯静态。如果偏要这样，build 的出来的dist 目录，你直接把这些静态文件扔进去也行
