### ISSUE TITLE
大神，项目的README.md可以更新下了哈，另外能否更完美点，把登录拦截器也加上来？

### ISSUE THREAD

**Issue by lgs3137** [lizhoukai/vue-mobile-cli#4]
大神，项目的README.md可以更新下了哈，另外能否更完美点，把登录拦截器也加上来？
新手，只能拿大神的作品瞻仰了~

**Comment by lizhoukai** [comment]
@lgs3137 README.md 更新下是啥意思 文档有漏吗？ 登录拦截器的话 你可以 util 目录下自己写一个哈。😀

**Comment by lgs3137** [comment]
额，工程目录规范那里的路径稍微调整了下，强迫症。。。
登录拦截的在学着写。。。

**Comment by lizhoukai** [comment]
@lgs3137 拦截器 已加
